apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: maze-web
  name: maze-web
  namespace: maze-web
spec:
  failedBuildsHistoryLimit: 3
  output:
    to:
      kind: ImageStreamTag
      name: maze-web:latest
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/mxmeinhold/maze-generator
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  successfulBuildsHistoryLimit: 3
  triggers:
  - type: ConfigChange
  - generic:
      secretReference:
        name: "maze-web-generic"
    type: Generic
  - github:
      secretReference:
        name: "maze-web-github"
    type: GitHub
